import { Board, BoardHistory } from "../types/game";

const emptyBoard: Board = [
  [
    { value: null, row: 0, col: 0, name: "a1" },
    { value: null, row: 0, col: 1, name: "a2" },
    { value: null, row: 0, col: 2, name: "a3" },
    { value: null, row: 0, col: 3, name: "a4" },
    { value: null, row: 0, col: 4, name: "a5" },
    { value: null, row: 0, col: 5, name: "a6" },
    { value: null, row: 0, col: 6, name: "a7" },
  ],
  [
    { value: null, row: 1, col: 0, name: "b1" },
    { value: null, row: 1, col: 1, name: "b2" },
    { value: null, row: 1, col: 2, name: "b3" },
    { value: null, row: 1, col: 3, name: "b4" },
    { value: null, row: 1, col: 4, name: "b5" },
    { value: null, row: 1, col: 5, name: "b6" },
    { value: null, row: 1, col: 6, name: "b7" },
  ],
  [
    { value: null, row: 2, col: 0, name: "c1" },
    { value: null, row: 2, col: 1, name: "c2" },
    { value: null, row: 2, col: 2, name: "c3" },
    { value: null, row: 2, col: 3, name: "c4" },
    { value: null, row: 2, col: 4, name: "c5" },
    { value: null, row: 2, col: 5, name: "c6" },
    { value: null, row: 2, col: 6, name: "c7" },
  ],
  [
    { value: null, row: 3, col: 0, name: "d1" },
    { value: null, row: 3, col: 1, name: "d2" },
    { value: null, row: 3, col: 2, name: "d3" },
    { value: null, row: 3, col: 3, name: "d4" },
    { value: null, row: 3, col: 4, name: "d5" },
    { value: null, row: 3, col: 5, name: "d6" },
    { value: null, row: 3, col: 6, name: "d7" },
  ],
  [
    { value: null, row: 4, col: 0, name: "e1" },
    { value: null, row: 4, col: 1, name: "e2" },
    { value: null, row: 4, col: 2, name: "e3" },
    { value: null, row: 4, col: 3, name: "e4" },
    { value: null, row: 4, col: 4, name: "e5" },
    { value: null, row: 4, col: 5, name: "e6" },
    { value: null, row: 4, col: 6, name: "e7" },
  ],
  [
    { value: null, row: 5, col: 0, name: "f1" },
    { value: null, row: 5, col: 1, name: "f2" },
    { value: null, row: 5, col: 2, name: "f3" },
    { value: null, row: 5, col: 3, name: "f4" },
    { value: null, row: 5, col: 4, name: "f5" },
    { value: null, row: 5, col: 5, name: "f6" },
    { value: null, row: 5, col: 6, name: "f7" },
  ],
];

const fullBoard: Board = [
  [
    { value: "p2", row: 0, col: 0, name: "a1" },
    { value: "p2", row: 0, col: 1, name: "a2" },
    { value: "p1", row: 0, col: 2, name: "a3" },
    { value: "p1", row: 0, col: 3, name: "a4" },
    { value: "p1", row: 0, col: 4, name: "a5" },
    { value: "p2", row: 0, col: 5, name: "a6" },
    { value: "p2", row: 0, col: 6, name: "a7" },
  ],
  [
    { value: "p2", row: 1, col: 0, name: "b1" },
    { value: "p1", row: 1, col: 1, name: "b2" },
    { value: "p1", row: 1, col: 2, name: "b3" },
    { value: "p2", row: 1, col: 3, name: "b4" },
    { value: "p2", row: 1, col: 4, name: "b5" },
    { value: "p1", row: 1, col: 5, name: "b6" },
    { value: "p1", row: 1, col: 6, name: "b7" },
  ],
  [
    { value: "p1", row: 2, col: 0, name: "c1" },
    { value: "p2", row: 2, col: 1, name: "c2" },
    { value: "p1", row: 2, col: 2, name: "c3" },
    { value: "p1", row: 2, col: 3, name: "c4" },
    { value: "p1", row: 2, col: 4, name: "c5" },
    { value: "p2", row: 2, col: 5, name: "c6" },
    { value: "p2", row: 2, col: 6, name: "c7" },
  ],
  [
    { value: "p1", row: 3, col: 0, name: "d1" },
    { value: "p1", row: 3, col: 1, name: "d2" },
    { value: "p2", row: 3, col: 2, name: "d3" },
    { value: "p2", row: 3, col: 3, name: "d4" },
    { value: "p2", row: 3, col: 4, name: "d5" },
    { value: "p1", row: 3, col: 5, name: "d6" },
    { value: "p1", row: 3, col: 6, name: "d7" },
  ],
  [
    { value: "p2", row: 4, col: 0, name: "e1" },
    { value: "p2", row: 4, col: 1, name: "e2" },
    { value: "p2", row: 4, col: 2, name: "e3" },
    { value: "p1", row: 4, col: 3, name: "e4" },
    { value: "p1", row: 4, col: 4, name: "e5" },
    { value: "p2", row: 4, col: 5, name: "e6" },
    { value: "p2", row: 4, col: 6, name: "e7" },
  ],
  [
    { value: "p1", row: 5, col: 0, name: "f1" },
    { value: "p2", row: 5, col: 1, name: "f2" },
    { value: "p1", row: 5, col: 2, name: "f3" },
    { value: "p2", row: 5, col: 3, name: "f4" },
    { value: "p1", row: 5, col: 4, name: "f5" },
    { value: "p1", row: 5, col: 5, name: "f6" },
    { value: "p2", row: 5, col: 6, name: "f7" },
  ],
];

const historyToBoard: (BoardHistory | Board)[][] = [
  [
    [
      1, -1, 1, -1, 1, -1, 2, -2, 2, -2, 2, -2, 3, -3, 3, -3, 3, -3, 4, -4, 4,
      -4, 4, -4, 5, -5, 5, -5, 5, -5, 6, -6, 6, -6, 6, -6, 7, -7, 7, -7, 7, -7,
    ],
    [
      [
        { value: "p1", row: 0, col: 0, name: "a1" },
        { value: "p1", row: 0, col: 1, name: "a2" },
        { value: "p1", row: 0, col: 2, name: "a3" },
        { value: "p1", row: 0, col: 3, name: "a4" },
        { value: "p1", row: 0, col: 4, name: "a5" },
        { value: "p1", row: 0, col: 5, name: "a6" },
        { value: "p1", row: 0, col: 6, name: "a7" },
      ],
      [
        { value: "p2", row: 1, col: 0, name: "b1" },
        { value: "p2", row: 1, col: 1, name: "b2" },
        { value: "p2", row: 1, col: 2, name: "b3" },
        { value: "p2", row: 1, col: 3, name: "b4" },
        { value: "p2", row: 1, col: 4, name: "b5" },
        { value: "p2", row: 1, col: 5, name: "b6" },
        { value: "p2", row: 1, col: 6, name: "b7" },
      ],
      [
        { value: "p1", row: 2, col: 0, name: "c1" },
        { value: "p1", row: 2, col: 1, name: "c2" },
        { value: "p1", row: 2, col: 2, name: "c3" },
        { value: "p1", row: 2, col: 3, name: "c4" },
        { value: "p1", row: 2, col: 4, name: "c5" },
        { value: "p1", row: 2, col: 5, name: "c6" },
        { value: "p1", row: 2, col: 6, name: "c7" },
      ],
      [
        { value: "p2", row: 3, col: 0, name: "d1" },
        { value: "p2", row: 3, col: 1, name: "d2" },
        { value: "p2", row: 3, col: 2, name: "d3" },
        { value: "p2", row: 3, col: 3, name: "d4" },
        { value: "p2", row: 3, col: 4, name: "d5" },
        { value: "p2", row: 3, col: 5, name: "d6" },
        { value: "p2", row: 3, col: 6, name: "d7" },
      ],
      [
        { value: "p1", row: 4, col: 0, name: "e1" },
        { value: "p1", row: 4, col: 1, name: "e2" },
        { value: "p1", row: 4, col: 2, name: "e3" },
        { value: "p1", row: 4, col: 3, name: "e4" },
        { value: "p1", row: 4, col: 4, name: "e5" },
        { value: "p1", row: 4, col: 5, name: "e6" },
        { value: "p1", row: 4, col: 6, name: "e7" },
      ],
      [
        { value: "p2", row: 5, col: 0, name: "f1" },
        { value: "p2", row: 5, col: 1, name: "f2" },
        { value: "p2", row: 5, col: 2, name: "f3" },
        { value: "p2", row: 5, col: 3, name: "f4" },
        { value: "p2", row: 5, col: 4, name: "f5" },
        { value: "p2", row: 5, col: 5, name: "f6" },
        { value: "p2", row: 5, col: 6, name: "f7" },
      ],
    ],
  ],
  [
    [
      1, -2, 3, -4, 5, -6, 7, -7, 6, -5, 4, -3, 2, -1, 1, -2, 3, -4, 5, -6, 7,
      -7, 6, -5, 4, -3, 2, -1, 1, -2, 3, -4, 5, -6, 7, -7, 6, -5, 4, -3, 2, -1,
    ],
    [
      [
        { value: "p1", row: 0, col: 0, name: "a1" },
        { value: "p2", row: 0, col: 1, name: "a2" },
        { value: "p1", row: 0, col: 2, name: "a3" },
        { value: "p2", row: 0, col: 3, name: "a4" },
        { value: "p1", row: 0, col: 4, name: "a5" },
        { value: "p2", row: 0, col: 5, name: "a6" },
        { value: "p1", row: 0, col: 6, name: "a7" },
      ],
      [
        { value: "p2", row: 1, col: 0, name: "b1" },
        { value: "p1", row: 1, col: 1, name: "b2" },
        { value: "p2", row: 1, col: 2, name: "b3" },
        { value: "p1", row: 1, col: 3, name: "b4" },
        { value: "p2", row: 1, col: 4, name: "b5" },
        { value: "p1", row: 1, col: 5, name: "b6" },
        { value: "p2", row: 1, col: 6, name: "b7" },
      ],
      [
        { value: "p1", row: 2, col: 0, name: "c1" },
        { value: "p2", row: 2, col: 1, name: "c2" },
        { value: "p1", row: 2, col: 2, name: "c3" },
        { value: "p2", row: 2, col: 3, name: "c4" },
        { value: "p1", row: 2, col: 4, name: "c5" },
        { value: "p2", row: 2, col: 5, name: "c6" },
        { value: "p1", row: 2, col: 6, name: "c7" },
      ],
      [
        { value: "p2", row: 3, col: 0, name: "d1" },
        { value: "p1", row: 3, col: 1, name: "d2" },
        { value: "p2", row: 3, col: 2, name: "d3" },
        { value: "p1", row: 3, col: 3, name: "d4" },
        { value: "p2", row: 3, col: 4, name: "d5" },
        { value: "p1", row: 3, col: 5, name: "d6" },
        { value: "p2", row: 3, col: 6, name: "d7" },
      ],
      [
        { value: "p1", row: 4, col: 0, name: "e1" },
        { value: "p2", row: 4, col: 1, name: "e2" },
        { value: "p1", row: 4, col: 2, name: "e3" },
        { value: "p2", row: 4, col: 3, name: "e4" },
        { value: "p1", row: 4, col: 4, name: "e5" },
        { value: "p2", row: 4, col: 5, name: "e6" },
        { value: "p1", row: 4, col: 6, name: "e7" },
      ],
      [
        { value: "p2", row: 5, col: 0, name: "f1" },
        { value: "p1", row: 5, col: 1, name: "f2" },
        { value: "p2", row: 5, col: 2, name: "f3" },
        { value: "p1", row: 5, col: 3, name: "f4" },
        { value: "p2", row: 5, col: 4, name: "f5" },
        { value: "p1", row: 5, col: 5, name: "f6" },
        { value: "p2", row: 5, col: 6, name: "f7" },
      ],
    ],
  ],
  [
    [1, 1, 1, -2, -2, -2],
    [
      [
        { value: "p1", row: 0, col: 0, name: "a1" },
        { value: "p2", row: 0, col: 1, name: "a2" },
        { value: null, row: 0, col: 2, name: "a3" },
        { value: null, row: 0, col: 3, name: "a4" },
        { value: null, row: 0, col: 4, name: "a5" },
        { value: null, row: 0, col: 5, name: "a6" },
        { value: null, row: 0, col: 6, name: "a7" },
      ],
      [
        { value: "p1", row: 1, col: 0, name: "b1" },
        { value: "p2", row: 1, col: 1, name: "b2" },
        { value: null, row: 1, col: 2, name: "b3" },
        { value: null, row: 1, col: 3, name: "b4" },
        { value: null, row: 1, col: 4, name: "b5" },
        { value: null, row: 1, col: 5, name: "b6" },
        { value: null, row: 1, col: 6, name: "b7" },
      ],
      [
        { value: "p1", row: 2, col: 0, name: "c1" },
        { value: "p2", row: 2, col: 1, name: "c2" },
        { value: null, row: 2, col: 2, name: "c3" },
        { value: null, row: 2, col: 3, name: "c4" },
        { value: null, row: 2, col: 4, name: "c5" },
        { value: null, row: 2, col: 5, name: "c6" },
        { value: null, row: 2, col: 6, name: "c7" },
      ],
      [
        { value: null, row: 3, col: 0, name: "d1" },
        { value: null, row: 3, col: 1, name: "d2" },
        { value: null, row: 3, col: 2, name: "d3" },
        { value: null, row: 3, col: 3, name: "d4" },
        { value: null, row: 3, col: 4, name: "d5" },
        { value: null, row: 3, col: 5, name: "d6" },
        { value: null, row: 3, col: 6, name: "d7" },
      ],
      [
        { value: null, row: 4, col: 0, name: "e1" },
        { value: null, row: 4, col: 1, name: "e2" },
        { value: null, row: 4, col: 2, name: "e3" },
        { value: null, row: 4, col: 3, name: "e4" },
        { value: null, row: 4, col: 4, name: "e5" },
        { value: null, row: 4, col: 5, name: "e6" },
        { value: null, row: 4, col: 6, name: "e7" },
      ],
      [
        { value: null, row: 5, col: 0, name: "f1" },
        { value: null, row: 5, col: 1, name: "f2" },
        { value: null, row: 5, col: 2, name: "f3" },
        { value: null, row: 5, col: 3, name: "f4" },
        { value: null, row: 5, col: 4, name: "f5" },
        { value: null, row: 5, col: 5, name: "f6" },
        { value: null, row: 5, col: 6, name: "f7" },
      ],
    ],
  ],
];

export { emptyBoard, fullBoard, historyToBoard };
